// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWLSiFL6OwYojRwBIEOaIVSQgd2r_c5TM',
    appId: '1:954385867357:web:772f664a697c7b0be723b4',
    messagingSenderId: '954385867357',
    projectId: 'project-aether-c8171',
    authDomain: 'project-aether-c8171.firebaseapp.com',
    storageBucket: 'project-aether-c8171.firebasestorage.app',
    measurementId: 'G-CHQGMYK49Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM6uU6MwtfTFXvu-8fN5ZCAsCyJE9CLps',
    appId: '1:954385867357:android:51cba24c26019f53e723b4',
    messagingSenderId: '954385867357',
    projectId: 'project-aether-c8171',
    storageBucket: 'project-aether-c8171.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlzOh6XpBFJGhVTmIQgBqy1id7tmv0O1c',
    appId: '1:954385867357:ios:a2d26ac64d6ec533e723b4',
    messagingSenderId: '954385867357',
    projectId: 'project-aether-c8171',
    storageBucket: 'project-aether-c8171.firebasestorage.app',
    iosBundleId: 'com.example.aether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlzOh6XpBFJGhVTmIQgBqy1id7tmv0O1c',
    appId: '1:954385867357:ios:a2d26ac64d6ec533e723b4',
    messagingSenderId: '954385867357',
    projectId: 'project-aether-c8171',
    storageBucket: 'project-aether-c8171.firebasestorage.app',
    iosBundleId: 'com.example.aether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWLSiFL6OwYojRwBIEOaIVSQgd2r_c5TM',
    appId: '1:954385867357:web:65eb8ac3548c612ce723b4',
    messagingSenderId: '954385867357',
    projectId: 'project-aether-c8171',
    authDomain: 'project-aether-c8171.firebaseapp.com',
    storageBucket: 'project-aether-c8171.firebasestorage.app',
    measurementId: 'G-C4BCKHJM52',
  );
}
